src/Entity/BorrowerList.php
<?php

namespace App\Entity;

use App\Repository\BorrowerListRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BorrowerListRepository::class)]
class BorrowerList
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $borrowedDate = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $returnDate = null;

    #[ORM\Column(length: 255)]
    private ?string $Status = null;

    #[ORM\ManyToOne(inversedBy: 'borrowerLists')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Book $book = null;

    #[ORM\ManyToOne(inversedBy: 'borrowerLists')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $userbr = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBorrowedDate(): ?\DateTimeInterface
    {
        return $this->borrowedDate;
    }

    public function setBorrowedDate(\DateTimeInterface $borrowedDate): self
    {
        $this->borrowedDate = $borrowedDate;

        return $this;
    }

    public function getReturnDate(): ?\DateTimeInterface
    {
        return $this->returnDate;
    }

    public function setReturnDate(\DateTimeInterface $returnDate): self
    {
        $this->returnDate = $returnDate;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->Status;
    }

    public function setStatus(string $Status): self
    {
        $this->Status = $Status;

        return $this;
    }

    public function getBook(): ?Book
    {
        return $this->book;
    }

    public function setBook(?Book $book): self
    {
        $this->book = $book;

        return $this;
    }

    public function getUserbr(): ?User
    {
        return $this->userbr;
    }

    public function setUserbr(?User $userbr): self
    {
        $this->userbr = $userbr;

        return $this;
    }
 
   
}

src/Form/BorrowerListType.php
<?php

namespace App\Form;

use App\Entity\Book;
use App\Entity\BorrowerList;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BorrowerListType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('book', EntityType::class, ['class'=>Book::class, 'choice_label'=>'name'])
            ->add('userbr', EntityType::class, ['class'=>User::class, 'choice_label'=>'name'])
            ->add('borrowedDate', DateType::class)
            ->add('returnDate', DateType::class)
            ->add('Status', TextType::class)

            ->add('save', SubmitType::class)
        ;
        
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => BorrowerList::class,
        ]);
    }
}

src/Controller/BorrowerListController.php
<?php

namespace App\Controller;

use App\Entity\BorrowerList;
use App\Form\BorrowerListType;
use App\Repository\BorrowerListRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

    /**
     * @Route("/borrowerlist")
     */
    class BorrowerListController extends AbstractController
    {
        private BorrowerListRepository $repo;
        public function __construct(BorrowerListRepository $repo)
       {
          $this->repo = $repo;
       }
        /**
         * @Route("/", name="borrowerlist_show")
         */
        public function bookshowAction(): Response
        {
            $borrowerlist= $this->repo->findAll();
            return $this->render('borrower_list/index.html.twig', [
                'borrowerlist'=>$borrowerlist
            ]);
        }
          /**
          * @Route("/showborrowerlist", name="showborrowerlist")
          */
        public function showBorrowerList(): Response
        {
        $borrowerlist= $this->repo->findAll();
        return $this->render('borrower_list/show.html.twig', [
            'borrowerlist'=>$borrowerlist
        ]);
        }   
    
        /**
         * @Route("/{id}", name="borrowerlist_read",requirements={"id"="\d+"})
         */
        public function showAction(BorrowerList $bl): Response
        {
            return $this->render('detail.html.twig', [
                'bl'=>$bl
            ]);
        }
    
        /**
         * @Route("/add", name="borrowerlist_create")
         */
        public function createAction(Request $req, SluggerInterface $slugger): Response
        {
            
            $bl = new BorrowerList();
            $form = $this->createForm(BorrowerListType::class, $bl);
    
            $form->handleRequest($req);
            if($form->isSubmitted() && $form->isValid()){
                // if($b->getCreated()===null){
                //     $b->setCreated(new \DateTime());
                // }
                // $imgFile = $form->get('file')->getData();
                // if ($imgFile) {
                //     $newFilename = $this->uploadImage($imgFile,$slugger);
                //     $bl->setImage($newFilename);
                // }
                $this->repo->save($bl,true);
                return $this->redirectToRoute('borrowerlist_show', [], Response::HTTP_SEE_OTHER);
            }
            return $this->render("borrower_list/form.html.twig",[
                'form' => $form->createView()
            ]);
        }
    
    
    
        /**
         * @Route("/edit/{id}", name="borrowerlist_edit",requirements={"id"="\d+"})
         */
        public function editAction(Request $req, BorrowerList $bl,
        SluggerInterface $slugger): Response
        {
            
            $form = $this->createForm(BorrowerListType::class, $bl);   
    
            $form->handleRequest($req);
            if($form->isSubmitted() && $form->isValid()){
                // if($b->getCreated()===null){
                //     $b->setCreated(new \DateTime());
                // }
                // $imgFile = $form->get('file')->getData();
                // if ($imgFile) {
                //     $newFilename = $this->uploadImage($imgFile,$slugger);
                //     $b->setImage($newFilename);
                // }
                $this->repo->save($bl,true);
                return $this->redirectToRoute('borrowerlist_show', [], Response::HTTP_SEE_OTHER);
            }
            return $this->render("borrower_list/form.html.twig",[
                'form' => $form->createView()
            ]);
        }
    
        public function uploadImage($imgFile, SluggerInterface $slugger): ?string{
            $originalFilename = pathinfo($imgFile->getClientOriginalName(), PATHINFO_FILENAME);
            $safeFilename = $slugger->slug($originalFilename);
            $newFilename = $safeFilename.'-'.uniqid().'.'.$imgFile->guessExtension();
            try {
                $imgFile->move(
                    $this->getParameter('image_dir'),
                    $newFilename
                );
            } catch (FileException $e) {
                echo $e;
            }
            return $newFilename;
        }
    
        /**
         * @Route("/delete/{id}",name="borrowerlist_delete",requirements={"id"="\d+"})
         */
        
        public function deleteAction(Request $request, BorrowerList $bl): Response
        {
            $this->repo->remove($bl,true);
            return $this->redirectToRoute('borrowerlist_show', [], Response::HTTP_SEE_OTHER);
        }
    
}

templates/borrower_list/form.html.twig
{% extends "admin.html.twig" %}
{% block title %}
    Admin Page - Product
{% endblock %}
{% block body %}
      <div className="page-heading pb-2 mt-4 mb-2 ">
                <h3 style="text-align: center;" > Insert Borrwer</h3> <a href="{{path('borrowerlist_show')}}"><button type="button" class="btn btn-outline-primary">Back to index</button></a>
            </div>
            <div class="page-content mt-4">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            {# <form class="form form-vertical" method="POST" action="#"> #}
                            {{ form_start(form,{'attr':{'class':'form form-vertical'}} ) }}
                                <div class="form-body">
                                    <div class="row">
                                    
                                         <div class="col-12">
                                            <div class="form-group">
                                                <label for="contact-info-vertical">User Name</label>
                                                {{ form_widget(form.userbr, {'attr':{'placeholder':'author'}}) }}
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="first-name-vertical">Book name</label>
                                                {{ form_widget(form.book, {'attr':{'placeholder':'book Name'}}) }}
                                                {# <input type="text" id="pname" class="form-control"
                                                    name="Product_Name" placeholder="Product Name"
                                                    value =""> #}
                                            </div>
                                        </div>
                                       
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label for="first-name-vertical">Borrower Date</label>
                                                {{ form_widget(form.borrowedDate, {'attr':{'placeholder':'discription'}}) }}
                                            </div>
                                        </div>
                                         <div class="col-12">
                                            <div class="form-group">
                                                <label for="first-name-vertical">Return Date</label>
                                                {{ form_widget(form.returnDate, {'attr':{'placeholder':'discription'}}) }}
                                            </div>
                                        </div>
                                         <div class="col-12">
                                            <div class="form-group">
                                                <label for="first-name-vertical">Status</label>
                                                {{ form_widget(form.Status, {'attr':{'placeholder':'description'}}) }}
                                            </div>
                                        </div>
                                        
                                        {# <div class="col-12">
                                            <div class="form-group">
                                                <label for="contact-info-vertical">Quantity</label>
                                                {{ form_widget(form.quantity, {'attr':{'placeholder':'0-100'}}) }}
                                            </div>
                                        </div> #}
                                        {# <div class="col-12">
                                            <div class="form-group">
                                                <label for="image-vertical"> {{ form_label(form.file) }}</label>
                                               
                                                {{ form_widget(form.file) }}
                                            </div>
                                        </div>
                                        {{ form_widget(form.image) }}
                                         <div class="pt-3">
                                            {% set img = form.image.vars.value %}
                                                {% if img %}
                                                    <img src="{{asset('uploads/'~img)}}"
                                                class="w-25 shadow p-3 mb-5 bg-body rounded" />
                                                {% else %}
                                                    <img src="https://cdn2.iconfinder.com/data/icons/symbol-blue-set-3/100/Untitled-1-94-512.png"
                                                class="w-25 shadow p-3 mb-5 bg-body rounded" />
                                                {% endif %}
                                                
                                                
                                         </div> #}
                                         
                                        <div class="col-12 d-flex justify-content-end pt-2">
                                        
                                            {{ form_widget(form.save,{'attr':{'class':'btn btn-primary me-2'}}) }}
                                          <button type="reset"
                                                class="btn btn-secondary">Reset</button>
                                        </div>
                                    </div>
                                </div>
                            {# </form> #}
                            {{ form_end(form) }}
                        </div> <!--card body-->
                    
                    </div> <!--card content-->
                </div> <!--card-->
            </div><!--page content-->
{% endblock %}

templates/borrower_list/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}List Borrower Page!{% endblock %}

{% block body %}
  <div className="page-heading pb-2 mt-4 mb-2 ">
                    <h3 style="text-align: center;">List Borrwer Manager</h3> <a href="{{path('borrowerlist_create')}}"><button type="button" class="btn btn-outline-primary">Insert</button></a>
                </div>
                <div class="page-content">
                <div class="btn-group" role="group" aria-label="Basic outlined example">
               
                </div>
                <div class="card">
                    <div class="container mb-3">
                        <div class="table-responsive text-nowrap">
                      <table class="table table-striped">
                        <thead>
                          <tr>
                            <th>ID</th>
                            <th>User Name</th>
                            <th>Book Name</th>
                            <th>Borrowed Date</th>
                            <th>Return Date</th>
                            <th>Status</th>
                            {# <th>Quantity</th> #}
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody class="table-border-bottom-0">
                          {% for bl in borrowerlist %}
                              <tr>
                                  <td>{{ bl.id}}</td>
                                  <td>{{ bl.userbr}}</td>
                                  <td>{{ bl.book}}</td>
                                  <td>{{ bl.borrowedDate|date("m/d/Y")}}</td>
                                  <td>{{ bl.returnDate|date("m/d/Y")}}</td>
                                  <td>{{ bl.status}}</td>
                                  <td>
                                    <a href="{{path('borrowerlist_edit',{'id':bl.id})}}">Edit</a>
                                  <a href="{{path('borrowerlist_delete',{'id':bl.id})}}">Delete</a>
                                  </td>
                              </tr>
                          {% endfor %}
                          
                        </tbody>
                      </table>
                    </div>
                </div>
                </div>
                </div>
{% endblock %}

templates/borrower_list/show.html.twig
{% extends "home.html.twig" %}
{% block title %}
    Admin Page - Product
{% endblock %}
{% block body %}
<!--Main layout-->
<main>
<div class="container">
  <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: #1F8A70">
  <!-- Container wrapper -->
  <div class="container-fluid" style="margin-top: 50px;">

    <!-- Navbar brand -->
    <a class="navbar-brand" href="{{path('homepage')}}">View:</a>

    <!-- Toggle button -->
    <button 
       class="navbar-toggler" 
       type="button" 
       data-bs-toggle="collapse" 
       data-bs-target="#navbarSupportedContent2">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent2">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <!-- Link -->
        <li class="nav-item acitve">
          <a class="nav-link text-black" href="{{path('bookListShow')}}"><b>Book</b></a>
        </li>
        <li class="nav-item acitve">
          <a class="nav-link text-black" href="{{path('showauthorlist')}}"><b>Author</b></a>
        </li>
        <li class="nav-item acitve">
          <a class="nav-link text-black" href="{{path('showborrowerlist')}}"><b>List Borrower</b></a>
        </li>
        <li class="nav-item acitve">
          <a class="nav-link text-black" href="{{path('showbooktype')}}"><b>Book Type</b></a>
        </li>
          
      </ul>
      
      <!-- Search -->
      <form class="w-auto py-1" style="max-width: 12rem" action="{{path('SearchByName')}}">
        <input type="search" class="form-control rounded-0" placeholder="Search" aria-label="Search" name="name">
      </form>

    </div>
  </div>

            
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->
  <div className="page-heading pb-2 mt-4 mb-2 ">
                    {# <h3>Manager</h3> <a href="{{path('borrowerlist_create')}}"><button type="button" class="btn btn-outline-primary">Insert</button></a> #}
                </div>
                <div class="page-content">
                <div class="btn-group" role="group" aria-label="Basic outlined example">
               
                </div>
                <div class="card">
                    <div class="container mb-3">
                        <div class="table-responsive text-nowrap">
                      <table class="table table-striped">
                        <thead>
                          <tr>
                            <th>ID</th>
                            <th>User Name</th>
                            <th>Book Name</th>
                            <th>Borrowed Date</th>
                            <th>Return Date</th>
                            <th>Status</th>
                            {# <th>Quantity</th> #}
                            {# <th>Action</th> #}
                          </tr>
                        </thead>
                        <tbody class="table-border-bottom-0">
                          {% for bl in borrowerlist %}
                              <tr>
                                  <td>{{ bl.id}}</td>
                                  <td>{{ bl.userbr}}</td>
                                  <td>{{ bl.book}}</td>
                                  <td>{{ bl.borrowedDate|date("m/d/Y")}}</td>
                                  <td>{{ bl.returnDate|date("m/d/Y")}}</td>
                                  <td>{{ bl.status}}</td>
                                
                              </tr>
                          {% endfor %}
                          
                        </tbody>
                      </table>
                    </div>
                </div>
                </div>
                </div>
{% endblock %}